public class main {
    public static void main(String[] args) {
        appartment a1=new appartment();
        appartment a2=new appartment(true,true,true,true,10,10,"aa","aa");
        appartment a3=new appartment(false,false,false,false,5,5,"dad","awsdas");
        livingRoom li1=new livingRoom();
        livingRoom li2=new livingRoom(true,true,true,5,5,5,5,5);
        livingRoom li3=new livingRoom(false,false,false,10,10,10,10,10);
        bathroom ba1=new bathroom();
        bathroom ba2=new bathroom(true,true,true,true,true,3,3,3);
        bathroom ba3=new bathroom(false,false,false,false,false,4,4,4);
        bedroom be1=new bedroom();
        bedroom be2=new bedroom(true,true,true,true,true,3,"AA","aa");
        bedroom be3=new bedroom(false,false,false,false,false,5,"BB","bb");
        car ca1=new car();
        car ca2=new car(3,3,3,3,"AA","AA","aa","aa");
        car ca3=new car(4,4,4,4,"BB","BB","bb","bb");
        desktop d1=new desktop();
        desktop d2=new desktop("AA","AA","AA","AA","AA",3,3,3);
        desktop d3=new desktop("BB","BB","BB","BB","BB",5,5,5);
        smartphone s1=new smartphone();
        smartphone s2=new smartphone(3,3,3,3,true,"a","a","a","a");
        smartphone s3=new smartphone(5,5,5,5,false,"b","b","b","b");
        laptop l1=new laptop();
        laptop l2=new laptop("A","A","A","A",3,3,3,3);
        laptop l3=new laptop("B","B","B","B",5,5,5,5);
        chair c1=new chair();
        chair c2=new chair(1,1,1,1,1,1,1,"a","a","a","a");
        chair c3=new chair(3,3,3,3,3,3,3,"b","b","b","b");
        table t1=new table();
        table t2=new table(1,1,1,1,1,1,1,"a","a","a");
        table t3=new table(3,3,3,3,3,3,3,"b","b","b");
        System.out.println("a1: "+a1);
        System.out.println("a2: "+a2);
        System.out.println("a3: "+a3);
        System.out.println("li1: "+li1);
        System.out.println("li2: "+li2);
        System.out.println("li3: "+li3);
        System.out.println("ba1: "+ba1);
        System.out.println("ba2: "+ba2);
        System.out.println("ba3: "+ba3);
        System.out.println("be1: "+be1);
        System.out.println("be2: "+be2);
        System.out.println("be3: "+be3);
        System.out.println("ca1: "+ca1);
        System.out.println("ca2: "+ca2);
        System.out.println("ca3: "+ca3);
        System.out.println("d1: "+d1);
        System.out.println("d2: "+d2);
        System.out.println("d3: "+d3);
        System.out.println("s1: "+s1);
        System.out.println("s2: "+s2);
        System.out.println("s3: "+s3);
        System.out.println("l1: "+l1);
        System.out.println("l2: "+l2);
        System.out.println("l3: "+l3);
        System.out.println("c1: "+c1);
        System.out.println("c2: "+c2);
        System.out.println("c3: "+c3);
        System.out.println("t3: "+t1);
        System.out.println("t3: "+t2);
        System.out.println("t3: "+t3);
    }
}
